apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-api-deployment
  labels:
    app: budget-app-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budget-app-api
  template:
    metadata:
      labels:
        app: budget-app-api
    spec:
      containers:
        - name: budget-app-api
          image: jarczoslaw/budget-app-api:dev
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: budget-app-api-service
spec:
  selector:
    app: budget-app-api
  ports:
    - port: 80
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: budget-app-api-ingress
  labels:
    app: budget-app-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: budget-app-api-service
          servicePort: 80
