version: "3.3" # optional since v1.27.0
services:
  web:
    container_name: budget-app-api
    build: .
    ports:
      - "5000:80"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
