environment: development

label:
  name: budget-app-api

container:
  name: budget-app-api
  pullPolicy: Always
  image: jarczoslaw/budget-app-api
  tag: dev
  port: 80
replicas: 3

service:
  port: 80
  type: ClusterIP